In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_row', 1000)
df = pd.read_csv('Data\Train.csv')
df.head()

         ID                                               text       label
0  SUAVK39Z            I feel that it was better I dieAm happy  Depression
1  9JDAGUV3                       Why do I get hallucinations?       Drugs
2  419WR1LQ  I am stresseed due to lack of financial suppor...  Depression
3  6UY7DX6Q                             Why is life important?     Suicide
4  FYC0FTFB  How could I be helped to go through the depres...  Depression

In [4]:
train = df.iloc[:, :-1]
test = pd.read_csv('Data/Test.csv')
target = df.iloc[:, -1]

In [5]:
print(train.shape)
print(test.shape)
print(target.shape)

(616, 2)
(309, 2)
(616,)

In [6]:
text = pd.concat([train, test], ignore_index=True)
text.shape

(925, 2)

In [7]:
import re
import nltk
nltk.download('stopwords')

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yaçin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [9]:
corpus = []
for i in range(0, 925):
    feeling = re.sub('[^a-zA-Z]', ' ', str(text['text'][i]))
    feeling = feeling.lower()
    feeling = feeling.split()
    ps = PorterStemmer()
    feeling = [ps.stem(word) for word in feeling if not word in set(stopwords.words('english'))]
    feeling = ' '.join(feeling)
    corpus.append(feeling)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
result = cv.fit_transform(corpus).toarray()

In [11]:
result.shape

(925, 778)

In [12]:
dataframe = pd.DataFrame(result)
training = df.iloc[:,0].to_frame()
training = training.join(dataframe.iloc[:616,:])
training = training.join(target)
training.head()

         ID  0  1  2  3  4  5  6  7  8  9  10  ...  767  768  769  770  771  772  773  774  775  776  777       label
0  SUAVK39Z  0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0    0    0    0  Depression
1  9JDAGUV3  0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0    0    0    0       Drugs
2  419WR1LQ  0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0    0    0    0  Depression
3  6UY7DX6Q  0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0    0    0    0     Suicide
4  FYC0FTFB  0  0  0  0  0  0  0  0  0  0   0  ...    0    0    0    0    0    0    0    0    0    0    0  Depression

[5 rows x 780 columns]

In [13]:
training.shape

(616, 780)

In [14]:
testing = test.iloc[:,0].to_frame()
_test = dataframe.iloc[616:,:].reset_index()
_test.drop(columns = 'index', inplace = True)
testing = testing.join(_test)
testing.head()

         ID  0  1  2  3  4  5  6  7  8  9  10  11  ...  765  766  767  768  769  770  771  772  773  774  775  776  777
0  02V56KMO  0  0  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0
1  03BMGTOK  0  0  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0
2  03LZVFM6  0  0  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0
3  0EPULUM5  0  0  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0
4  0GM4C5GD  0  0  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0    0    0    0    0    0    0

[5 rows x 779 columns]

In [25]:
training['label']=training['label'].astype('category')
training['label']=training['label'].cat.codes
X = training.iloc[:,1:779].values
y = training.iloc[:,-1].values

In [26]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

y = to_categorical(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 0)

classifier = Sequential()

In [28]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 389, kernel_initializer = 'uniform', activation = 'relu', input_dim = 778))

# Adding the second hidden layer
classifier.add(Dense(units = 389, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
523/523 [==============================] - 1s 3ms/step - loss: 0.9891 - accuracy: 0.6119
Epoch 2/100
523/523 [==============================] - 0s 902us/step - loss: 0.6015 - accuracy: 0.7610
Epoch 3/100
523/523 [==============================] - 0s 665us/step - loss: 0.4757 - accuracy: 0.7763
Epoch 4/100
523/523 [==============================] - 0s 660us/step - loss: 0.3826 - accuracy: 0.8260
Epoch 5/100
523/523 [==============================] - 0s 673us/step - loss: 0.2621 - accuracy: 0.8910
Epoch 6/100
523/523 [==============================] - 0s 650us/step - loss: 0.2199 - accuracy: 0.9369
Epoch 7/100
523/523 [==============================] - 0s 673us/step - loss: 0.1580 - accuracy: 0.9522
Epoch 8/100
523/523 [==============================] - 0s 688us/step - loss: 0.1342 - accuracy: 0.9503
Epoch 9/100
523/523 [==============================] - 0s 658us/step - loss: 0.1027 - accuracy: 0.9713
Epoch 10/100
523/523 [==============================] - 0s 689us/step - loss: 0.0879 - accuracy: 0.9790
Epoch 11/100
523/523 [==============================] - 0s 788us/step - loss: 0.0703 - accuracy: 0.9751
Epoch 12/100
523/523 [==============================] - 0s 713us/step - loss: 0.0525 - accuracy: 0.9847
Epoch 13/100
523/523 [==============================] - 0s 696us/step - loss: 0.0537 - accuracy: 0.9885
Epoch 14/100
523/523 [==============================] - 0s 742us/step - loss: 0.0345 - accuracy: 0.9866
Epoch 15/100
523/523 [==============================] - 0s 720us/step - loss: 0.0434 - accuracy: 0.9866
Epoch 16/100
523/523 [==============================] - 0s 642us/step - loss: 0.0345 - accuracy: 0.9866
Epoch 17/100
523/523 [==============================] - 0s 658us/step - loss: 0.0113 - accuracy: 0.9962
Epoch 18/100
523/523 [==============================] - 0s 678us/step - loss: 0.0322 - accuracy: 0.9904
Epoch 19/100
523/523 [==============================] - 0s 681us/step - loss: 0.0230 - accuracy: 0.9924
Epoch 20/100
523/523 [==============================] - 0s 742us/step - loss: 0.0087 - accuracy: 0.9962
Epoch 21/100
523/523 [==============================] - 0s 849us/step - loss: 0.0245 - accuracy: 0.9924
Epoch 22/100
523/523 [==============================] - 0s 658us/step - loss: 0.0194 - accuracy: 0.9924
Epoch 23/100
523/523 [==============================] - 0s 718us/step - loss: 0.0257 - accuracy: 0.9866
Epoch 24/100
523/523 [==============================] - 0s 665us/step - loss: 0.0185 - accuracy: 0.9924
Epoch 25/100
523/523 [==============================] - 0s 665us/step - loss: 0.0181 - accuracy: 0.9943
Epoch 26/100
523/523 [==============================] - 0s 673us/step - loss: 0.0152 - accuracy: 0.9962
Epoch 27/100
523/523 [==============================] - 0s 665us/step - loss: 0.0227 - accuracy: 0.9943
Epoch 28/100
523/523 [==============================] - 0s 681us/step - loss: 0.0179 - accuracy: 0.9924
Epoch 29/100
523/523 [==============================] - 0s 696us/step - loss: 0.0181 - accuracy: 0.9943
Epoch 30/100
523/523 [==============================] - 0s 833us/step - loss: 0.0273 - accuracy: 0.9943
Epoch 31/100
523/523 [==============================] - 0s 675us/step - loss: 0.0201 - accuracy: 0.9962
Epoch 32/100
523/523 [==============================] - 0s 665us/step - loss: 0.0146 - accuracy: 0.9924
Epoch 33/100
523/523 [==============================] - 0s 719us/step - loss: 0.0452 - accuracy: 0.9943
Epoch 34/100
523/523 [==============================] - 0s 795us/step - loss: 0.0137 - accuracy: 0.9943
Epoch 35/100
523/523 [==============================] - 0s 658us/step - loss: 0.0152 - accuracy: 0.9981
Epoch 36/100
523/523 [==============================] - 0s 772us/step - loss: 0.0129 - accuracy: 0.9943
Epoch 37/100
523/523 [==============================] - 0s 726us/step - loss: 0.0441 - accuracy: 0.9943
Epoch 38/100
523/523 [==============================] - 0s 665us/step - loss: 0.0171 - accuracy: 0.9981
Epoch 39/100
523/523 [==============================] - 0s 841us/step - loss: 0.0127 - accuracy: 0.9981
Epoch 40/100
523/523 [==============================] - 0s 688us/step - loss: 0.0220 - accuracy: 0.9962
Epoch 41/100
523/523 [==============================] - 0s 658us/step - loss: 0.0232 - accuracy: 0.9943
Epoch 42/100
523/523 [==============================] - 0s 670us/step - loss: 0.0089 - accuracy: 0.9981
Epoch 43/100
523/523 [==============================] - 0s 681us/step - loss: 0.0091 - accuracy: 0.9981
Epoch 44/100
523/523 [==============================] - 0s 672us/step - loss: 0.0154 - accuracy: 0.9962
Epoch 45/100
523/523 [==============================] - 0s 674us/step - loss: 0.0221 - accuracy: 0.9943
Epoch 46/100
523/523 [==============================] - 0s 681us/step - loss: 0.0226 - accuracy: 0.9962
Epoch 47/100
523/523 [==============================] - 0s 673us/step - loss: 0.0417 - accuracy: 0.9943
Epoch 48/100
523/523 [==============================] - 0s 673us/step - loss: 0.0185 - accuracy: 0.9943
Epoch 49/100
523/523 [==============================] - 0s 658us/step - loss: 0.0109 - accuracy: 0.9962
Epoch 50/100
523/523 [==============================] - 0s 696us/step - loss: 0.0126 - accuracy: 0.9981
Epoch 51/100
523/523 [==============================] - 0s 658us/step - loss: 0.0155 - accuracy: 0.9981
Epoch 52/100
523/523 [==============================] - 0s 658us/step - loss: 0.0179 - accuracy: 0.9981
Epoch 53/100
523/523 [==============================] - 0s 665us/step - loss: 0.0138 - accuracy: 0.9981
Epoch 54/100
523/523 [==============================] - 0s 627us/step - loss: 0.0161 - accuracy: 0.9962
Epoch 55/100
523/523 [==============================] - 0s 619us/step - loss: 0.0200 - accuracy: 0.9943
Epoch 56/100
523/523 [==============================] - 0s 765us/step - loss: 0.0120 - accuracy: 0.9962
Epoch 57/100
523/523 [==============================] - 0s 742us/step - loss: 0.0099 - accuracy: 0.9981
Epoch 58/100
523/523 [==============================] - 0s 895us/step - loss: 0.0157 - accuracy: 0.9962
Epoch 59/100
523/523 [==============================] - 0s 859us/step - loss: 0.0121 - accuracy: 0.9981
Epoch 60/100
523/523 [==============================] - 0s 665us/step - loss: 0.0125 - accuracy: 0.9981
Epoch 61/100
523/523 [==============================] - 0s 696us/step - loss: 0.0101 - accuracy: 0.9981
Epoch 62/100
523/523 [==============================] - 0s 776us/step - loss: 0.0073 - accuracy: 0.9981
Epoch 63/100
523/523 [==============================] - 0s 795us/step - loss: 0.0164 - accuracy: 0.9962
Epoch 64/100
523/523 [==============================] - 0s 742us/step - loss: 0.0124 - accuracy: 0.9981
Epoch 65/100
523/523 [==============================] - 0s 726us/step - loss: 0.0074 - accuracy: 0.9981
Epoch 66/100
523/523 [==============================] - 0s 659us/step - loss: 0.0159 - accuracy: 0.9962
Epoch 67/100
523/523 [==============================] - 0s 707us/step - loss: 0.0082 - accuracy: 0.9981
Epoch 68/100
523/523 [==============================] - 0s 660us/step - loss: 0.0159 - accuracy: 0.9962
Epoch 69/100
523/523 [==============================] - 0s 696us/step - loss: 0.0103 - accuracy: 0.9962
Epoch 70/100
523/523 [==============================] - 0s 673us/step - loss: 0.0160 - accuracy: 0.9962
Epoch 71/100
523/523 [==============================] - 0s 671us/step - loss: 0.0129 - accuracy: 0.9962
Epoch 72/100
523/523 [==============================] - 0s 669us/step - loss: 0.0146 - accuracy: 0.9962
Epoch 73/100
523/523 [==============================] - 0s 738us/step - loss: 0.0044 - accuracy: 0.9981
Epoch 74/100
523/523 [==============================] - 0s 664us/step - loss: 0.0214 - accuracy: 0.9981
Epoch 75/100
523/523 [==============================] - 0s 677us/step - loss: 0.0153 - accuracy: 0.9962
Epoch 76/100
523/523 [==============================] - 0s 692us/step - loss: 0.0174 - accuracy: 0.9981
Epoch 77/100
523/523 [==============================] - 0s 647us/step - loss: 0.0175 - accuracy: 0.9962
Epoch 78/100
523/523 [==============================] - 0s 650us/step - loss: 0.0161 - accuracy: 0.9981
Epoch 79/100

523/523 [==============================] - 0s 647us/step - loss: 0.0122 - accuracy: 0.9962
Epoch 80/100
523/523 [==============================] - 0s 633us/step - loss: 0.0189 - accuracy: 0.9981
Epoch 81/100
523/523 [==============================] - 0s 620us/step - loss: 0.0106 - accuracy: 0.9981
Epoch 82/100
523/523 [==============================] - 0s 628us/step - loss: 0.0141 - accuracy: 0.9962
Epoch 83/100
523/523 [==============================] - 0s 772us/step - loss: 0.0089 - accuracy: 0.9981
Epoch 84/100
523/523 [==============================] - 0s 719us/step - loss: 0.0088 - accuracy: 0.9981
Epoch 85/100
523/523 [==============================] - 0s 719us/step - loss: 0.0148 - accuracy: 0.9962
Epoch 86/100
523/523 [==============================] - 0s 643us/step - loss: 0.0240 - accuracy: 0.9943
Epoch 87/100
523/523 [==============================] - 0s 655us/step - loss: 0.0155 - accuracy: 0.9962
Epoch 88/100
523/523 [==============================] - 0s 658us/step - loss: 0.0118 - accuracy: 0.9962
Epoch 89/100
523/523 [==============================] - 0s 661us/step - loss: 0.0112 - accuracy: 0.9962
Epoch 90/100
523/523 [==============================] - 0s 658us/step - loss: 0.0119 - accuracy: 0.9962
Epoch 91/100
523/523 [==============================] - 0s 656us/step - loss: 0.0104 - accuracy: 0.9962
Epoch 92/100
523/523 [==============================] - 0s 664us/step - loss: 0.0187 - accuracy: 0.9981
Epoch 93/100
523/523 [==============================] - 0s 664us/step - loss: 0.0096 - accuracy: 0.9981
Epoch 94/100
523/523 [==============================] - 0s 665us/step - loss: 0.0302 - accuracy: 0.9924
Epoch 95/100
523/523 [==============================] - 0s 688us/step - loss: 0.0276 - accuracy: 0.9962
Epoch 96/100
523/523 [==============================] - 0s 649us/step - loss: 0.0185 - accuracy: 0.9962
Epoch 97/100
523/523 [==============================] - 0s 740us/step - loss: 0.0127 - accuracy: 0.9981
Epoch 98/100
523/523 [==============================] - 0s 726us/step - loss: 0.0092 - accuracy: 0.9981
Epoch 99/100
523/523 [==============================] - 0s 674us/step - loss: 0.0117 - accuracy: 0.9981
Epoch 100/100
523/523 [==============================] - 0s 797us/step - loss: 0.0052 - accuracy: 0.9981

In [29]:
import numpy as np
y_pred = classifier.predict_proba(X_test)
np.around(y_pred, decimals=2)

array([[0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.93, 0.  , 0.07, 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.44, 0.56],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.36, 0.64],
       [1.  , 0.  , 0.  , 0.  ],
       [0.08, 0.  , 0.92, 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.98, 0.  , 0.02],
       [0.01, 0.  , 0.99, 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.36, 0.64],
       [0.  , 1.  , 0.  , 0.  ],
       [0.94, 0.  , 0.06, 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.96, 0.  , 0.04, 0.  ],
       [0.  , 0.97, 0.  , 0.03],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.88, 0.12],
       [0.  , 0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ]], dtype=float32)

In [30]:
y_test

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [31]:
Sub= testing.iloc[:,1:779].values
preds = classifier.predict_proba(Sub)
preds = np.around(preds, decimals=3)

In [32]:
Submission = testing.iloc[:, 0].to_frame()
 # Depression,Alcohol,Suicide,Drugs
Submission['Depression']=preds[:,1]
Submission['Alcohol']=preds[:,0]
Submission['Drugs']=preds[:,2]
Submission['Suicide']=preds[:,3]
Submission.head(10)

         ID  Depression  Alcohol  Drugs  Suicide
0  02V56KMO         1.0    0.000  0.000    0.000
1  03BMGTOK         1.0    0.000  0.000    0.000
2  03LZVFM6         1.0    0.000  0.000    0.000
3  0EPULUM5         1.0    0.000  0.000    0.000
4  0GM4C5GD         0.0    0.001  0.999    0.000
5  0IYM8BYT         0.0    0.000  0.039    0.961
6  0JFJVD28         0.0    0.000  0.000    1.000
7  0OZGUFOF         1.0    0.000  0.000    0.000
8  0WP999ZX         0.0    1.000  0.000    0.000
9  0ZA45Y5F         0.0    1.000  0.000    0.000

In [33]:
test.head(10)

         ID                                               text
0  02V56KMO          How to overcome bad feelings and emotions
1  03BMGTOK                     I feel like giving up in life
2  03LZVFM6  I was so depressed feel like got no strength t...
3  0EPULUM5  I feel so low especially since I had no one to...
4  0GM4C5GD       can i be successful when I am a drug addict?
5  0IYM8BYT        I am dissapointed,I need a sense of closure
6  0JFJVD28                                        I lost hope
7  0OZGUFOF                     I feel unloved and uncared for
8  0WP999ZX  What are factors that leads to addiction of al...
9  0ZA45Y5F      Is the advice of drinking moderatly ,prudent?

In [34]:
Submission.to_csv('Submissions/Submission_v5.csv', index=False)